# Generated by Django 5.0.4 on 2024-04-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
    ]
