# Generated by Django 5.0.4 on 2024-04-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
